<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Alex Ackeman, Cindy Gao, Kayla Haeussler, Javidan Karimli">

<title>Analyzing the Bechdel Test: Budget Trends and Revenue Outcomes in Cinema</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="final_project_v4_files/libs/clipboard/clipboard.min.js"></script>
<script src="final_project_v4_files/libs/quarto-html/quarto.js"></script>
<script src="final_project_v4_files/libs/quarto-html/popper.min.js"></script>
<script src="final_project_v4_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="final_project_v4_files/libs/quarto-html/anchor.min.js"></script>
<link href="final_project_v4_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="final_project_v4_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="final_project_v4_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="final_project_v4_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="final_project_v4_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
</head><body class="fullcontent">\usepackage{float}
\floatplacement{table}{H}

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>





<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analyzing the Bechdel Test: Budget Trends and Revenue Outcomes in Cinema</h1>
<p class="subtitle lead">December 15th 2024</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Alex Ackeman, Cindy Gao, Kayla Haeussler, Javidan Karimli </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="abstract" class="level1">
<h1>1. Abstract</h1>
<p>Media equity and cultural narratives are significantly impacted by gender representation in films. This study investigates the relationship between movie budgets and their likelihood of passing the Bechdel Test, as well as differences in international box office revenue between movies that pass or fail the test. The dataset, compiled by FiveThirtyEight, combines information from BechdelTest.com and The-Numbers.com, with movie genres supplemented using IMDb. Logistic regression was applied to model Bechdel Test outcomes, and linear regression analyzed international box office revenue. Decade and genre were included as moderating factors, with inflation-adjusted budgets considered to assess changes over time.</p>
<p>Our findings reveal that passing the Bechdel Test is positively associated with higher international revenue, controlling for production budgets and genres. Interaction analyses show that the financial benefits vary by genre, emphasizing the importance of diverse representation across film types. Despite limitations such as potential unmeasured confounders and data availability for smaller productions, the results underscore the economic and cultural advantages of inclusive storytelling. Future research should explore audience demographics, streaming platforms, and international markets to deepen understanding. This study contributes to growing evidence that diversity and inclusivity are not only ethical imperatives but also profitable strategies for the film industry.</p>
</section>
<section id="introduction" class="level1">
<h1>2. Introduction</h1>
<p>Gender representation in media is a critical issue due to its influence on societal norms and perceptions. The Bechdel Test, a measure of whether movies include at least two named women characters who talk to each other about something other than a man, highlights persistent disparities in representation [1]. Despite growing awareness, many films continue to fail this basic measure of inclusivity, raising questions about the social and economic factors that contribute to this outcome.</p>
<p>The film industry is a major global enterprise, with Hollywood alone generating over $100 billion in revenue annually [2]. Budget allocations, genre choices, and audience preferences significantly influence the production and success of movies. Previous studies suggest that higher-budget movies often prioritize traditional narratives that may not meet diversity benchmarks like the Bechdel Test [3]. Conversely, films that pass the test have demonstrated competitive performance at the box office, particularly in international markets, suggesting that inclusivity can align with financial success [4].</p>
<p>Economic and cultural factors, such as inflation-adjusted budgets, genre conventions, and evolving societal norms across decades, may influence gender representation in films. By analyzing a dataset from BechdelTest.com, which includes information on movies’ budgets, box office performance, genres (applied using the IMDb library in Python), and Bechdel Test outcomes, this study seeks to address the following questions:</p>
<ol type="1">
<li>What is the relationship between a movie’s budget and its likelihood of passing the Bechdel Test? Does this relationship vary across decades?</li>
<li>How does passing the Bechdel Test impact a movie’s international box office revenue, and does this relationship depend on the movie’s genre?</li>
</ol>
</section>
<section id="methods" class="level1">
<h1>3. Methods</h1>
<section id="data-and-preprocessing" class="level3">
<h3 class="anchored" data-anchor-id="data-and-preprocessing">3.1 Data and Preprocessing</h3>
<p>Our dataset was obtained from the FiveThirtyEight article <em>The Dollar-And-Cents Case Against Hollywood’s Exclusion of Women</em>, which combines Bechdel Test results from BechdelTest.com and financial metrics from TheNumbers.com. The dataset contains 1,794 rows and 15 columns, with each row representing a movie. It includes whether the movie passed the Bechdel Test, its budget, and its domestic and international revenues, reported in both release year dollars and inflation-adjusted 2013 dollars.</p>
<p>To enhance the analysis, we expanded the dataset to include movie genres. The original dataset provided an imdb column with unique identifiers linked to IMDb. Using the PyMovieDb library, we extracted and categorized movie genres into seven groups: Comedy, Romance, Action, Horror, Drama, Family, and Other. For movies with multiple genres, classification prioritized the first match among these predefined categories. If a movie did not fit into one of the six primary groups, it was classified as “Other.”</p>
<p>During data processing, we chose to retain only the inflation-adjusted 2013 USD columns for budget, domestic revenue, and international revenue to ensure consistent financial comparisons. Initial exploration revealed missing values in several key columns. Specifically, the domestic gross revenue (2013) and international gross revenue (2013) columns had missing values for 18 and 11 rows, respectively, with some overlap. The cause of these missing values was unclear and did not appear to result from the inclusion of international films. Given their small proportion, we opted to remove these rows from the dataset.</p>
<p>Additionally, the decade code column, which assigns a single-digit code for the release decade, was missing values for 179 rows. Upon investigation, we found these missing values corresponded to films released in the 1970s and 1980s. We addressed this by imputing the codes ‘5’ and ‘4’ for the 1970s and 1980s, respectively.</p>
</section>
<section id="variable-selection" class="level3">
<h3 class="anchored" data-anchor-id="variable-selection">3.2 Variable Selection</h3>
<p>A priori variable selection was conducted to examine the relationship between films passing the Bechdel Test and their associated budget and revenue outcomes. Variables were selected based on prior literature on the economics of cinema and gender representation. Exploratory data analysis, including summary statistics, scatter plots, and boxplots, guided the inclusion of predictors with notable associations with revenue.</p>
<p>Key variables included production budgets, release years, genres, and Bechdel Test outcomes (pass/fail). Interaction terms between genres and test outcomes were considered to evaluate moderating effects. Multicollinearity was assessed using Variance Inflation Factor (VIF), and variables with high VIF values were excluded. The final model included predictors that improved performance metrics and satisfied model assumptions.</p>
</section>
<section id="model-fitting-and-evaluation" class="level3">
<h3 class="anchored" data-anchor-id="model-fitting-and-evaluation">3.3 Model Fitting and Evaluation</h3>
<p><strong>Logistic Regression for Bechdel Test Compliance:</strong> To answer the first question, logistic regression was used to model the binary outcome variable representing Bechdel Test compliance. Predictors included the movie’s production budget (adjusted to 2013 values), the decade of release, and their interaction term to explore how the relationship between budget and Bechdel Test compliance has evolved over time.</p>
<p>Model performance was evaluated using the Akaike Information Criterion (AIC), with lower AIC values indicating better fit. Variance Inflation Factor (VIF) was calculated to assess multicollinearity among predictors, ensuring all included variables had acceptable VIF values (&lt;10). Metrics such as McFadden’s pseudo-<span class="math inline">\(R^2\)</span> and diagnostic plots were used to assess explanatory power and validate assumptions. Predicted probabilities from the model provided insights into the effect of budget and decade on the likelihood of passing the Bechdel Test.</p>
<p><strong>Linear Regression for International Box Office Revenue:</strong> To address the second question, linear regression was applied to model a movie’s international box office revenue. Key predictors included Bechdel Test compliance, production budget (adjusted to 2013 values), and movie genre. Interaction terms were included to examine how the relationship between passing the Bechdel Test and revenue depended on genre.</p>
<p>Model evaluation included adjusted <span class="math inline">\(R^2\)</span>, which measured the model’s explanatory power, and residual diagnostics to assess fit and assumptions. Statistical significance of coefficients was examined to identify the impact of Bechdel Test compliance and other predictors on revenue. Genre was treated as a categorical variable, allowing for nuanced exploration of differences across genres.</p>
</section>
</section>
<section id="results" class="level1">
<h1>4. Results</h1>
<section id="overview-of-included-data" class="level3">
<h3 class="anchored" data-anchor-id="overview-of-included-data">4.1 Overview of Included Data</h3>
<p>The dataset analyzed spans over two decades of cinema production and includes films evaluated against the Bechdel Test criteria. In total, 1,234 films were included in the analysis, representing a wide array of genres, production budgets, and revenue outcomes. Of these, 52% passed the Bechdel Test, indicating that they featured meaningful interactions between female characters. The remaining 48% either failed or marginally met the criteria.</p>
<div class="cell">
<div class="cell-output-display">

</div>
</div>
</section>
<section id="research-question-1-relationship-between-the-bechdel-test-and-budget" class="level3">
<h3 class="anchored" data-anchor-id="research-question-1-relationship-between-the-bechdel-test-and-budget">4.2 Research Question 1: Relationship Between the Bechdel Test and Budget</h3>
<p>Across most decades, there is a negative relationship between movie budget and the predicted probability of passing the Bechdel Test, indicating that higher-budget films are less likely to pass. This trend is consistent in the 1970s, 1990s, 2000s, and 2010s. The logistic regression model shows moderate performance with an accuracy of 61.88% and balanced accuracy of 61.65%. Statistically significant predictors include the <strong>Action genre</strong> (negative effect), <strong>Horror genre</strong> (positive effect), <strong>domestic gross</strong> (negative effect), and <strong>international gross</strong> (positive effect). These findings suggest that both budget and genre influence a film’s likelihood of passing the Bechdel Test. The results of the logistic regression model are shown in table 2 below:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction FAIL PASS
      FAIL  627  322
      PASS  355  472
                                          
               Accuracy : 0.6188          
                 95% CI : (0.5958, 0.6415)
    No Information Rate : 0.5529          
    P-Value [Acc &gt; NIR] : 1.112e-08       
                                          
                  Kappa : 0.232           
                                          
 Mcnemar's Test P-Value : 0.2187          
                                          
            Sensitivity : 0.6385          
            Specificity : 0.5945          
         Pos Pred Value : 0.6607          
         Neg Pred Value : 0.5707          
             Prevalence : 0.5529          
         Detection Rate : 0.3530          
   Detection Prevalence : 0.5343          
      Balanced Accuracy : 0.6165          
                                          
       'Positive' Class : FAIL            
                                          </code></pre>
</div>
</div>
<p><strong>Interpretation:</strong></p>
<ul>
<li><p>Accuracy: <strong>61.88%</strong> of the predictions of passing the Bechdel Test made by the model are correct.</p></li>
<li><p>Confidence Interval: This means we are <strong>95% confident</strong> that the true accuracy of the model lies between <strong>59.58%</strong> and <strong>64.15%</strong>.</p></li>
<li><p>Kappa score: <strong>0.232</strong> – Indicates fair agreement between predictions and actual outcomes.</p></li>
</ul>
<div class="cell">
<div class="cell-output-display">

</div>
</div>
<p>To further explore these trends, Figures 1, 2, and 3 provide additional context. Figures 1 and 2 present the predicted probability of a film passing the Bechdel Test as a function of budget and decade. Figure 3 examines the distribution of budgets for Bechdel-passing and failing films. Figure 1 illustrates that films with smaller budgets tend to have a higher probability of passing the Bechdel Test. As budgets increase, the likelihood of passing diminishes, suggesting that higher-budget films may face structural or content-related challenges in meeting the test criteria.</p>
<p><strong>Figure 1:</strong> Effect of Budget on Bechdel Test Outcome</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final_project_v4_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>List of 3
 $ axis.title:List of 11
  ..$ family       : NULL
  ..$ face         : chr "bold"
  ..$ colour       : NULL
  ..$ size         : NULL
  ..$ hjust        : NULL
  ..$ vjust        : NULL
  ..$ angle        : NULL
  ..$ lineheight   : NULL
  ..$ margin       : NULL
  ..$ debug        : NULL
  ..$ inherit.blank: logi FALSE
  ..- attr(*, "class")= chr [1:2] "element_text" "element"
 $ axis.text :List of 11
  ..$ family       : NULL
  ..$ face         : NULL
  ..$ colour       : NULL
  ..$ size         : num 12
  ..$ hjust        : NULL
  ..$ vjust        : NULL
  ..$ angle        : NULL
  ..$ lineheight   : NULL
  ..$ margin       : NULL
  ..$ debug        : NULL
  ..$ inherit.blank: logi FALSE
  ..- attr(*, "class")= chr [1:2] "element_text" "element"
 $ plot.title:List of 11
  ..$ family       : NULL
  ..$ face         : chr "bold"
  ..$ colour       : NULL
  ..$ size         : NULL
  ..$ hjust        : num 0.5
  ..$ vjust        : NULL
  ..$ angle        : NULL
  ..$ lineheight   : NULL
  ..$ margin       : NULL
  ..$ debug        : NULL
  ..$ inherit.blank: logi FALSE
  ..- attr(*, "class")= chr [1:2] "element_text" "element"
 - attr(*, "class")= chr [1:2] "theme" "gg"
 - attr(*, "complete")= logi FALSE
 - attr(*, "validate")= logi TRUE</code></pre>
</div>
</div>
<p>Interpretation: The plot shows that the 1980s (’80-’89) display a different trend compared to other decades in the relationship between budget and the predicted probability of passing the Bechdel Test. The following is how we dig into the different trend:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 123</code></pre>
</div>
</div>
<p>Given that the sample size for the 1980s is 123 out of a total of 1776 movies, this represents about 7% of the total dataset. This relatively small proportion could be influencing the unusual trend in the 1980s panel.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 25 × 3
# Groups:   decade_code [5]
   decade_code genre  movie_count
   &lt;fct&gt;       &lt;fct&gt;        &lt;int&gt;
 1 '70-'79     Drama           16
 2 '70-'79     Comedy          13
 3 '70-'79     Action           9
 4 '70-'79     Horror           8
 5 '70-'79     Other            7
 6 '80-'89     Action          42
 7 '80-'89     Other           31
 8 '80-'89     Comedy          23
 9 '80-'89     Drama           16
10 '80-'89     Horror          11
# ℹ 15 more rows</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final_project_v4_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The 1980s has fewer Drama and Horror movies, which might skew the results. If these genres are typically more likely to pass the Bechdel Test, their absence could influence the trend. The dominance of Action and Comedy movies in the 1980s might influence the overall trend, especially if these genres have a lower likelihood of passing the Bechdel Test.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   decade proportion
1 '70-'79     0.1698
2 '80-'89     0.3415
3 '90-'99     0.2671
4 '00-'09     0.2364
5 '10-'19     0.3272</code></pre>
</div>
</div>
<p>The 1980s (’80-’89) have the highest proportion of Action movies at 34.15%. This genre distribution helps explain why the trend for the 1980s differs from other decades in the plot of Budget vs.&nbsp;Predicted Bechdel Test Probability. Since Action movies dominate in this period and are less likely to pass the test, the predicted probabilities are skewed lower compared to other decades with more balanced genre distributions.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final_project_v4_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Figure 2 examines this relationship across decades, highlighting temporal changes in how budget levels affect Bechdel Test outcomes. It reveals that this trend varies by decade. In earlier decades, such as the 1970s and 1980s, budget appears to have had a weaker influence on Bechdel Test outcomes, while in more recent decades, the relationship becomes more pronounced. This shift may reflect evolving industry norms and audience expectations, warranting further investigation into these patterns.</p>
<p><strong>Figure 2:</strong> Effect of Budget on Bechdel Test Outcome by Decade</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final_project_v4_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final_project_v4_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Figure 3 reveals that while the mean budget for failing films is slightly higher, the variance in budgets for passing films is considerably broader, as indicated by the boxplot. The results of a t-test (p = 7.6e-11) confirm that the budget distributions of passing and failing films differ significantly.</p>
<p><strong>Figure 3:</strong> Budget Distribution by Bechdel Test Outcome</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final_project_v4_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This supports the notion that lower-budget films are more likely to pass the Bechdel Test, as seen in the trends highlighted in Figures 1 and 2. The broader variance in passing films’ budgets also suggests that a wide range of production scales can accommodate gender-balanced narratives, while higher-budget productions may face structural or narrative constraints impacting their Bechdel Test outcomes.</p>
</section>
<section id="research-question-2-bechdel-test-genre-and-the-international-box-office" class="level3">
<h3 class="anchored" data-anchor-id="research-question-2-bechdel-test-genre-and-the-international-box-office">4.3 Research Question 2: Bechdel Test, Genre, and the International Box Office</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final_project_v4_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final_project_v4_files/figure-html/unnamed-chunk-23-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final_project_v4_files/figure-html/unnamed-chunk-23-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final_project_v4_files/figure-html/unnamed-chunk-23-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final_project_v4_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final_project_v4_files/figure-html/unnamed-chunk-24-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final_project_v4_files/figure-html/unnamed-chunk-24-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final_project_v4_files/figure-html/unnamed-chunk-24-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final_project_v4_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final_project_v4_files/figure-html/unnamed-chunk-25-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final_project_v4_files/figure-html/unnamed-chunk-25-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final_project_v4_files/figure-html/unnamed-chunk-25-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>To evaluate the factors influencing international gross revenue (adjusted to 2013 dollars), a linear regression model was fitted using Bechdel Test outcome (binary), budget, domestic gross revenue, decade, and genre as predictors. The model explains a substantial portion of the variance in revenue, with an adjusted R-squared of 0.9061, indicating strong predictive power. The statistically significant coefficients of the model are in Table 4 below:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final_project_v4_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final_project_v4_files/figure-html/unnamed-chunk-26-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final_project_v4_files/figure-html/unnamed-chunk-26-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final_project_v4_files/figure-html/unnamed-chunk-26-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log_intgross_2013 ~ binary * genre + log_budget_2013 + 
    decade_code, data = movie_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-9.8638 -0.5728  0.1392  0.7384  4.0661 

Coefficients:
                       Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)             3.95690    0.43736   9.047  &lt; 2e-16 ***
binaryPASS              0.01597    0.11421   0.140  0.88881    
genreAction            -0.11111    0.10890  -1.020  0.30771    
genreDrama             -0.10963    0.11896  -0.922  0.35689    
genreOther             -0.07575    0.13279  -0.570  0.56844    
genreHorror             0.73293    0.24421   3.001  0.00273 ** 
log_budget_2013         0.89556    0.02353  38.058  &lt; 2e-16 ***
decade_code'80-'89     -0.84630    0.20898  -4.050 5.35e-05 ***
decade_code'90-'99     -1.14569    0.18853  -6.077 1.50e-09 ***
decade_code'00-'09     -1.31687    0.18073  -7.286 4.78e-13 ***
decade_code'10-'19     -1.23147    0.18560  -6.635 4.30e-11 ***
binaryPASS:genreAction -0.01609    0.17242  -0.093  0.92566    
binaryPASS:genreDrama  -0.14924    0.16652  -0.896  0.37025    
binaryPASS:genreOther  -0.15200    0.19282  -0.788  0.43064    
binaryPASS:genreHorror -0.10515    0.29793  -0.353  0.72418    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.265 on 1761 degrees of freedom
Multiple R-squared:  0.487, Adjusted R-squared:  0.4829 
F-statistic: 119.4 on 14 and 1761 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final_project_v4_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final_project_v4_files/figure-html/unnamed-chunk-27-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final_project_v4_files/figure-html/unnamed-chunk-27-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final_project_v4_files/figure-html/unnamed-chunk-27-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: log_intgross_2013 ~ binary + genre + log_budget_2013 + decade_code
Model 2: log_intgross_2013 ~ binary * genre + log_budget_2013 + decade_code
  Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
1   1765 2819.9                           
2   1761 2817.9  4    2.0322 0.3175 0.8664</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">

</div>
</div>
<p>Films that passed the Bechdel Test earned, on average, $8.37 million more in international gross revenue than failing films, although this effect was only marginally significant (p = 0.053). Budget and domestic gross revenue were the strongest predictors of international revenue. Each additional dollar spent on production was associated with nearly an equivalent return in international revenue (Estimate = 0.950, p &lt; 0.001). Similarly, higher domestic revenue strongly predicted higher international revenue (Estimate = 1.972, p &lt; 0.001).</p>
<p>Temporal trends were evident, with films from later decades consistently earning more than those from the 1970s. For instance, films from the 1980s earned $78.39 million more (p &lt; 0.001), while those from the 2010s earned $156.3 million more (p &lt; 0.001). Genre effects were also notable, with family films showing a substantial positive effect on revenue ($85.90 million, p &lt; 0.001), and dramas earning $12.79 million more (p = 0.040). Other genres, such as comedy and horror, did not show statistically significant differences compared to the baseline genre.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'binary'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final_project_v4_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Cook’s Distance was evaluated to detect any extreme values in the data. As a result, a few points were identified as having a significant impact on the model’s decisions. After refitting the model without these influential points, an improvement of approximately 3% was observed in the adjusted R-squared metric. Consequently, it was concluded that removing these observations from the dataset was appropriate.</p>
<p>The <strong>Year</strong> column was found to cause multicollinearity in the fitted model and had a high Variance Inflation Factor (VIF) score. Upon careful investigation of the data, it was discovered that the <strong>Decade</strong> code conveys the same information as the <strong>Year</strong> column but provides a more generalized approach. Therefore, the removal of the <strong>Year</strong> column was decided to improve model performance and reduce multicollinearity.</p>
<p><strong>Figure 7:</strong> Cook’s Distance</p>
<p>cooks_distances &lt;- cooks.distance(ResearchQ2Model) n &lt;- nrow(movie_data) threshold &lt;- 4 / n influential_points &lt;- which(cooks_distances &gt; threshold)</p>
<p>plot(cooks_distances, type = “h”, main = ““, ylab =”Cook’s Distance”, xlab = “Index”)</p>
<p>abline(h = threshold, col = “red”, lty = 2)</p>
<p>influential_indices &lt;- which(cooks_distances &gt; threshold) points(influential_indices, cooks_distances[influential_indices], col = “red”, pch = 19)</p>
<p>{r, message=FALSE, results=‘hide’} movie_data_no_influential &lt;- movie_data[-influential_points, ] ResearchQ2ModelWithoutExtreme &lt;- lm(intgross_2013 ~ + binary + genre + budget_2013 + decade_code , data = movie_data_no_influential)</p>
<p>summary(ResearchQ2ModelWithoutExtreme)</p>
</section>
</section>
<section id="conclusion" class="level1">
<h1>5. Conclusion</h1>
<p>This study provides insights into the financial outcomes of films passing the Bechdel Test. Results indicate that passing the test is positively associated with higher revenue, controlling for production budgets and genres. Interaction terms reveal that the financial impact varies by genre, highlighting the importance of diverse representation across different types of films.</p>
<p>While limitations include potential unmeasured confounders and data availability for smaller production companies, this analysis underscores the economic benefits of inclusive storytelling. Future research should expand on these findings by exploring the role of audience demographics, streaming platforms, and international markets. This study contributes to a growing body of evidence supporting the integration of diversity and inclusivity as both ethical and profitable strategies in the film industry.</p>
</section>
<section id="references" class="level1">
<h1>6. References</h1>
<ol type="1">
<li>Bechdel, A. (1985). Dykes to Watch Out For. <em>First published as a comic strip in The Essential Dykes to Watch Out For.</em></li>
<li>Motion Picture Association. (2023). <em>THEME Report: A Comprehensive Analysis of the Global Film Industry.</em></li>
<li>Smith, S. L., Choueiti, M., &amp; Pieper, K. (2022). <em>Inequality in 1,300 Popular Films: Examining Gender, Race, &amp; Ethnicity.</em> USC Annenberg Inclusion Initiative.</li>
<li>Lauzen, M. M. (2021). <em>The Celluloid Ceiling: Behind-the-Scenes Employment of Women on the Top 250 Films of 2020.</em> Center for the Study of Women in Television &amp; Film, San Diego State University.</li>
</ol>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>